// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connect_plugins.proto

// Protobuf Java Version: 3.25.3
package zingg.spark.connect.proto;

public final class ConnectPlugins {
  private ConnectPlugins() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubmitZinggJob_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubmitZinggJob_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025connect_plugins.proto\">\n\016SubmitZinggJo" +
      "b\022\022\n\004args\030\001 \001(\tR\004args\022\030\n\007options\030\002 \001(\tR\007" +
      "optionsB\035\n\031zingg.spark.connect.protoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SubmitZinggJob_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SubmitZinggJob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubmitZinggJob_descriptor,
        new java.lang.String[] { "Args", "Options", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
