// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connect_plugins.proto

// Protobuf Java Version: 3.25.3
package zingg.spark.connect.proto;

public interface SubmitZinggJobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubmitZinggJob)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
   * @return Whether the argumnets field is set.
   */
  boolean hasArgumnets();
  /**
   * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
   * @return The argumnets.
   */
  zingg.spark.connect.proto.Arguments getArgumnets();
  /**
   * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
   */
  zingg.spark.connect.proto.ArgumentsOrBuilder getArgumnetsOrBuilder();

  /**
   * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
   * @return Whether the cliOptions field is set.
   */
  boolean hasCliOptions();
  /**
   * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
   * @return The cliOptions.
   */
  zingg.spark.connect.proto.ClientOptions getCliOptions();
  /**
   * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
   */
  zingg.spark.connect.proto.ClientOptionsOrBuilder getCliOptionsOrBuilder();

  /**
   * <pre>
   * The next message is a serialized LogicalPlan
   * </pre>
   *
   * <code>optional bytes in_memory_date = 3 [json_name = "inMemoryDate"];</code>
   * @return Whether the inMemoryDate field is set.
   */
  boolean hasInMemoryDate();
  /**
   * <pre>
   * The next message is a serialized LogicalPlan
   * </pre>
   *
   * <code>optional bytes in_memory_date = 3 [json_name = "inMemoryDate"];</code>
   * @return The inMemoryDate.
   */
  com.google.protobuf.ByteString getInMemoryDate();
}
