// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connect_plugins.proto

// Protobuf Java Version: 3.25.3
package zingg.spark.connect.proto;

/**
 * Protobuf type {@code SubmitZinggJob}
 */
public final class SubmitZinggJob extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SubmitZinggJob)
    SubmitZinggJobOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubmitZinggJob.newBuilder() to construct.
  private SubmitZinggJob(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubmitZinggJob() {
    args_ = "";
    options_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubmitZinggJob();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return zingg.spark.connect.proto.ConnectPlugins.internal_static_SubmitZinggJob_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return zingg.spark.connect.proto.ConnectPlugins.internal_static_SubmitZinggJob_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            zingg.spark.connect.proto.SubmitZinggJob.class, zingg.spark.connect.proto.SubmitZinggJob.Builder.class);
  }

  public static final int ARGS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object args_ = "";
  /**
   * <code>string args = 1 [json_name = "args"];</code>
   * @return The args.
   */
  @java.lang.Override
  public java.lang.String getArgs() {
    java.lang.Object ref = args_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      args_ = s;
      return s;
    }
  }
  /**
   * <code>string args = 1 [json_name = "args"];</code>
   * @return The bytes for args.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArgsBytes() {
    java.lang.Object ref = args_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      args_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPTIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object options_ = "";
  /**
   * <code>string options = 2 [json_name = "options"];</code>
   * @return The options.
   */
  @java.lang.Override
  public java.lang.String getOptions() {
    java.lang.Object ref = options_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      options_ = s;
      return s;
    }
  }
  /**
   * <code>string options = 2 [json_name = "options"];</code>
   * @return The bytes for options.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOptionsBytes() {
    java.lang.Object ref = options_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      options_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(args_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, args_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(options_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, options_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(args_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, args_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(options_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, options_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof zingg.spark.connect.proto.SubmitZinggJob)) {
      return super.equals(obj);
    }
    zingg.spark.connect.proto.SubmitZinggJob other = (zingg.spark.connect.proto.SubmitZinggJob) obj;

    if (!getArgs()
        .equals(other.getArgs())) return false;
    if (!getOptions()
        .equals(other.getOptions())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ARGS_FIELD_NUMBER;
    hash = (53 * hash) + getArgs().hashCode();
    hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
    hash = (53 * hash) + getOptions().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static zingg.spark.connect.proto.SubmitZinggJob parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static zingg.spark.connect.proto.SubmitZinggJob parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(zingg.spark.connect.proto.SubmitZinggJob prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SubmitZinggJob}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SubmitZinggJob)
      zingg.spark.connect.proto.SubmitZinggJobOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zingg.spark.connect.proto.ConnectPlugins.internal_static_SubmitZinggJob_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zingg.spark.connect.proto.ConnectPlugins.internal_static_SubmitZinggJob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zingg.spark.connect.proto.SubmitZinggJob.class, zingg.spark.connect.proto.SubmitZinggJob.Builder.class);
    }

    // Construct using zingg.spark.connect.proto.SubmitZinggJob.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      args_ = "";
      options_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return zingg.spark.connect.proto.ConnectPlugins.internal_static_SubmitZinggJob_descriptor;
    }

    @java.lang.Override
    public zingg.spark.connect.proto.SubmitZinggJob getDefaultInstanceForType() {
      return zingg.spark.connect.proto.SubmitZinggJob.getDefaultInstance();
    }

    @java.lang.Override
    public zingg.spark.connect.proto.SubmitZinggJob build() {
      zingg.spark.connect.proto.SubmitZinggJob result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public zingg.spark.connect.proto.SubmitZinggJob buildPartial() {
      zingg.spark.connect.proto.SubmitZinggJob result = new zingg.spark.connect.proto.SubmitZinggJob(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(zingg.spark.connect.proto.SubmitZinggJob result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.args_ = args_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.options_ = options_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof zingg.spark.connect.proto.SubmitZinggJob) {
        return mergeFrom((zingg.spark.connect.proto.SubmitZinggJob)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(zingg.spark.connect.proto.SubmitZinggJob other) {
      if (other == zingg.spark.connect.proto.SubmitZinggJob.getDefaultInstance()) return this;
      if (!other.getArgs().isEmpty()) {
        args_ = other.args_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getOptions().isEmpty()) {
        options_ = other.options_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              args_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              options_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object args_ = "";
    /**
     * <code>string args = 1 [json_name = "args"];</code>
     * @return The args.
     */
    public java.lang.String getArgs() {
      java.lang.Object ref = args_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        args_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string args = 1 [json_name = "args"];</code>
     * @return The bytes for args.
     */
    public com.google.protobuf.ByteString
        getArgsBytes() {
      java.lang.Object ref = args_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        args_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string args = 1 [json_name = "args"];</code>
     * @param value The args to set.
     * @return This builder for chaining.
     */
    public Builder setArgs(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      args_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string args = 1 [json_name = "args"];</code>
     * @return This builder for chaining.
     */
    public Builder clearArgs() {
      args_ = getDefaultInstance().getArgs();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string args = 1 [json_name = "args"];</code>
     * @param value The bytes for args to set.
     * @return This builder for chaining.
     */
    public Builder setArgsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      args_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object options_ = "";
    /**
     * <code>string options = 2 [json_name = "options"];</code>
     * @return The options.
     */
    public java.lang.String getOptions() {
      java.lang.Object ref = options_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        options_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string options = 2 [json_name = "options"];</code>
     * @return The bytes for options.
     */
    public com.google.protobuf.ByteString
        getOptionsBytes() {
      java.lang.Object ref = options_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        options_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string options = 2 [json_name = "options"];</code>
     * @param value The options to set.
     * @return This builder for chaining.
     */
    public Builder setOptions(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      options_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string options = 2 [json_name = "options"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOptions() {
      options_ = getDefaultInstance().getOptions();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string options = 2 [json_name = "options"];</code>
     * @param value The bytes for options to set.
     * @return This builder for chaining.
     */
    public Builder setOptionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      options_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SubmitZinggJob)
  }

  // @@protoc_insertion_point(class_scope:SubmitZinggJob)
  private static final zingg.spark.connect.proto.SubmitZinggJob DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new zingg.spark.connect.proto.SubmitZinggJob();
  }

  public static zingg.spark.connect.proto.SubmitZinggJob getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubmitZinggJob>
      PARSER = new com.google.protobuf.AbstractParser<SubmitZinggJob>() {
    @java.lang.Override
    public SubmitZinggJob parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubmitZinggJob> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubmitZinggJob> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public zingg.spark.connect.proto.SubmitZinggJob getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

