// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connect_plugins.proto

// Protobuf Java Version: 3.25.3
package zingg.spark.connect.proto;

/**
 * Protobuf type {@code SubmitZinggJob}
 */
public final class SubmitZinggJob extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SubmitZinggJob)
    SubmitZinggJobOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubmitZinggJob.newBuilder() to construct.
  private SubmitZinggJob(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubmitZinggJob() {
    inMemoryDate_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubmitZinggJob();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return zingg.spark.connect.proto.ConnectPlugins.internal_static_SubmitZinggJob_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return zingg.spark.connect.proto.ConnectPlugins.internal_static_SubmitZinggJob_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            zingg.spark.connect.proto.SubmitZinggJob.class, zingg.spark.connect.proto.SubmitZinggJob.Builder.class);
  }

  private int bitField0_;
  public static final int ARGUMNETS_FIELD_NUMBER = 1;
  private zingg.spark.connect.proto.Arguments argumnets_;
  /**
   * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
   * @return Whether the argumnets field is set.
   */
  @java.lang.Override
  public boolean hasArgumnets() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
   * @return The argumnets.
   */
  @java.lang.Override
  public zingg.spark.connect.proto.Arguments getArgumnets() {
    return argumnets_ == null ? zingg.spark.connect.proto.Arguments.getDefaultInstance() : argumnets_;
  }
  /**
   * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
   */
  @java.lang.Override
  public zingg.spark.connect.proto.ArgumentsOrBuilder getArgumnetsOrBuilder() {
    return argumnets_ == null ? zingg.spark.connect.proto.Arguments.getDefaultInstance() : argumnets_;
  }

  public static final int CLI_OPTIONS_FIELD_NUMBER = 2;
  private zingg.spark.connect.proto.ClientOptions cliOptions_;
  /**
   * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
   * @return Whether the cliOptions field is set.
   */
  @java.lang.Override
  public boolean hasCliOptions() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
   * @return The cliOptions.
   */
  @java.lang.Override
  public zingg.spark.connect.proto.ClientOptions getCliOptions() {
    return cliOptions_ == null ? zingg.spark.connect.proto.ClientOptions.getDefaultInstance() : cliOptions_;
  }
  /**
   * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
   */
  @java.lang.Override
  public zingg.spark.connect.proto.ClientOptionsOrBuilder getCliOptionsOrBuilder() {
    return cliOptions_ == null ? zingg.spark.connect.proto.ClientOptions.getDefaultInstance() : cliOptions_;
  }

  public static final int IN_MEMORY_DATE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString inMemoryDate_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * The next message is a serialized LogicalPlan
   * </pre>
   *
   * <code>optional bytes in_memory_date = 3 [json_name = "inMemoryDate"];</code>
   * @return Whether the inMemoryDate field is set.
   */
  @java.lang.Override
  public boolean hasInMemoryDate() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * The next message is a serialized LogicalPlan
   * </pre>
   *
   * <code>optional bytes in_memory_date = 3 [json_name = "inMemoryDate"];</code>
   * @return The inMemoryDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getInMemoryDate() {
    return inMemoryDate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getArgumnets());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getCliOptions());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBytes(3, inMemoryDate_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getArgumnets());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCliOptions());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, inMemoryDate_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof zingg.spark.connect.proto.SubmitZinggJob)) {
      return super.equals(obj);
    }
    zingg.spark.connect.proto.SubmitZinggJob other = (zingg.spark.connect.proto.SubmitZinggJob) obj;

    if (hasArgumnets() != other.hasArgumnets()) return false;
    if (hasArgumnets()) {
      if (!getArgumnets()
          .equals(other.getArgumnets())) return false;
    }
    if (hasCliOptions() != other.hasCliOptions()) return false;
    if (hasCliOptions()) {
      if (!getCliOptions()
          .equals(other.getCliOptions())) return false;
    }
    if (hasInMemoryDate() != other.hasInMemoryDate()) return false;
    if (hasInMemoryDate()) {
      if (!getInMemoryDate()
          .equals(other.getInMemoryDate())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasArgumnets()) {
      hash = (37 * hash) + ARGUMNETS_FIELD_NUMBER;
      hash = (53 * hash) + getArgumnets().hashCode();
    }
    if (hasCliOptions()) {
      hash = (37 * hash) + CLI_OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getCliOptions().hashCode();
    }
    if (hasInMemoryDate()) {
      hash = (37 * hash) + IN_MEMORY_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getInMemoryDate().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static zingg.spark.connect.proto.SubmitZinggJob parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static zingg.spark.connect.proto.SubmitZinggJob parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static zingg.spark.connect.proto.SubmitZinggJob parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(zingg.spark.connect.proto.SubmitZinggJob prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SubmitZinggJob}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SubmitZinggJob)
      zingg.spark.connect.proto.SubmitZinggJobOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zingg.spark.connect.proto.ConnectPlugins.internal_static_SubmitZinggJob_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zingg.spark.connect.proto.ConnectPlugins.internal_static_SubmitZinggJob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zingg.spark.connect.proto.SubmitZinggJob.class, zingg.spark.connect.proto.SubmitZinggJob.Builder.class);
    }

    // Construct using zingg.spark.connect.proto.SubmitZinggJob.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getArgumnetsFieldBuilder();
        getCliOptionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      argumnets_ = null;
      if (argumnetsBuilder_ != null) {
        argumnetsBuilder_.dispose();
        argumnetsBuilder_ = null;
      }
      cliOptions_ = null;
      if (cliOptionsBuilder_ != null) {
        cliOptionsBuilder_.dispose();
        cliOptionsBuilder_ = null;
      }
      inMemoryDate_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return zingg.spark.connect.proto.ConnectPlugins.internal_static_SubmitZinggJob_descriptor;
    }

    @java.lang.Override
    public zingg.spark.connect.proto.SubmitZinggJob getDefaultInstanceForType() {
      return zingg.spark.connect.proto.SubmitZinggJob.getDefaultInstance();
    }

    @java.lang.Override
    public zingg.spark.connect.proto.SubmitZinggJob build() {
      zingg.spark.connect.proto.SubmitZinggJob result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public zingg.spark.connect.proto.SubmitZinggJob buildPartial() {
      zingg.spark.connect.proto.SubmitZinggJob result = new zingg.spark.connect.proto.SubmitZinggJob(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(zingg.spark.connect.proto.SubmitZinggJob result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.argumnets_ = argumnetsBuilder_ == null
            ? argumnets_
            : argumnetsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cliOptions_ = cliOptionsBuilder_ == null
            ? cliOptions_
            : cliOptionsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.inMemoryDate_ = inMemoryDate_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof zingg.spark.connect.proto.SubmitZinggJob) {
        return mergeFrom((zingg.spark.connect.proto.SubmitZinggJob)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(zingg.spark.connect.proto.SubmitZinggJob other) {
      if (other == zingg.spark.connect.proto.SubmitZinggJob.getDefaultInstance()) return this;
      if (other.hasArgumnets()) {
        mergeArgumnets(other.getArgumnets());
      }
      if (other.hasCliOptions()) {
        mergeCliOptions(other.getCliOptions());
      }
      if (other.hasInMemoryDate()) {
        setInMemoryDate(other.getInMemoryDate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getArgumnetsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getCliOptionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              inMemoryDate_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private zingg.spark.connect.proto.Arguments argumnets_;
    private com.google.protobuf.SingleFieldBuilderV3<
        zingg.spark.connect.proto.Arguments, zingg.spark.connect.proto.Arguments.Builder, zingg.spark.connect.proto.ArgumentsOrBuilder> argumnetsBuilder_;
    /**
     * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
     * @return Whether the argumnets field is set.
     */
    public boolean hasArgumnets() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
     * @return The argumnets.
     */
    public zingg.spark.connect.proto.Arguments getArgumnets() {
      if (argumnetsBuilder_ == null) {
        return argumnets_ == null ? zingg.spark.connect.proto.Arguments.getDefaultInstance() : argumnets_;
      } else {
        return argumnetsBuilder_.getMessage();
      }
    }
    /**
     * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
     */
    public Builder setArgumnets(zingg.spark.connect.proto.Arguments value) {
      if (argumnetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        argumnets_ = value;
      } else {
        argumnetsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
     */
    public Builder setArgumnets(
        zingg.spark.connect.proto.Arguments.Builder builderForValue) {
      if (argumnetsBuilder_ == null) {
        argumnets_ = builderForValue.build();
      } else {
        argumnetsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
     */
    public Builder mergeArgumnets(zingg.spark.connect.proto.Arguments value) {
      if (argumnetsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          argumnets_ != null &&
          argumnets_ != zingg.spark.connect.proto.Arguments.getDefaultInstance()) {
          getArgumnetsBuilder().mergeFrom(value);
        } else {
          argumnets_ = value;
        }
      } else {
        argumnetsBuilder_.mergeFrom(value);
      }
      if (argumnets_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
     */
    public Builder clearArgumnets() {
      bitField0_ = (bitField0_ & ~0x00000001);
      argumnets_ = null;
      if (argumnetsBuilder_ != null) {
        argumnetsBuilder_.dispose();
        argumnetsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
     */
    public zingg.spark.connect.proto.Arguments.Builder getArgumnetsBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getArgumnetsFieldBuilder().getBuilder();
    }
    /**
     * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
     */
    public zingg.spark.connect.proto.ArgumentsOrBuilder getArgumnetsOrBuilder() {
      if (argumnetsBuilder_ != null) {
        return argumnetsBuilder_.getMessageOrBuilder();
      } else {
        return argumnets_ == null ?
            zingg.spark.connect.proto.Arguments.getDefaultInstance() : argumnets_;
      }
    }
    /**
     * <code>.Arguments argumnets = 1 [json_name = "argumnets"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        zingg.spark.connect.proto.Arguments, zingg.spark.connect.proto.Arguments.Builder, zingg.spark.connect.proto.ArgumentsOrBuilder> 
        getArgumnetsFieldBuilder() {
      if (argumnetsBuilder_ == null) {
        argumnetsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            zingg.spark.connect.proto.Arguments, zingg.spark.connect.proto.Arguments.Builder, zingg.spark.connect.proto.ArgumentsOrBuilder>(
                getArgumnets(),
                getParentForChildren(),
                isClean());
        argumnets_ = null;
      }
      return argumnetsBuilder_;
    }

    private zingg.spark.connect.proto.ClientOptions cliOptions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        zingg.spark.connect.proto.ClientOptions, zingg.spark.connect.proto.ClientOptions.Builder, zingg.spark.connect.proto.ClientOptionsOrBuilder> cliOptionsBuilder_;
    /**
     * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
     * @return Whether the cliOptions field is set.
     */
    public boolean hasCliOptions() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
     * @return The cliOptions.
     */
    public zingg.spark.connect.proto.ClientOptions getCliOptions() {
      if (cliOptionsBuilder_ == null) {
        return cliOptions_ == null ? zingg.spark.connect.proto.ClientOptions.getDefaultInstance() : cliOptions_;
      } else {
        return cliOptionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
     */
    public Builder setCliOptions(zingg.spark.connect.proto.ClientOptions value) {
      if (cliOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cliOptions_ = value;
      } else {
        cliOptionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
     */
    public Builder setCliOptions(
        zingg.spark.connect.proto.ClientOptions.Builder builderForValue) {
      if (cliOptionsBuilder_ == null) {
        cliOptions_ = builderForValue.build();
      } else {
        cliOptionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
     */
    public Builder mergeCliOptions(zingg.spark.connect.proto.ClientOptions value) {
      if (cliOptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          cliOptions_ != null &&
          cliOptions_ != zingg.spark.connect.proto.ClientOptions.getDefaultInstance()) {
          getCliOptionsBuilder().mergeFrom(value);
        } else {
          cliOptions_ = value;
        }
      } else {
        cliOptionsBuilder_.mergeFrom(value);
      }
      if (cliOptions_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
     */
    public Builder clearCliOptions() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cliOptions_ = null;
      if (cliOptionsBuilder_ != null) {
        cliOptionsBuilder_.dispose();
        cliOptionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
     */
    public zingg.spark.connect.proto.ClientOptions.Builder getCliOptionsBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getCliOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
     */
    public zingg.spark.connect.proto.ClientOptionsOrBuilder getCliOptionsOrBuilder() {
      if (cliOptionsBuilder_ != null) {
        return cliOptionsBuilder_.getMessageOrBuilder();
      } else {
        return cliOptions_ == null ?
            zingg.spark.connect.proto.ClientOptions.getDefaultInstance() : cliOptions_;
      }
    }
    /**
     * <code>.ClientOptions cli_options = 2 [json_name = "cliOptions"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        zingg.spark.connect.proto.ClientOptions, zingg.spark.connect.proto.ClientOptions.Builder, zingg.spark.connect.proto.ClientOptionsOrBuilder> 
        getCliOptionsFieldBuilder() {
      if (cliOptionsBuilder_ == null) {
        cliOptionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            zingg.spark.connect.proto.ClientOptions, zingg.spark.connect.proto.ClientOptions.Builder, zingg.spark.connect.proto.ClientOptionsOrBuilder>(
                getCliOptions(),
                getParentForChildren(),
                isClean());
        cliOptions_ = null;
      }
      return cliOptionsBuilder_;
    }

    private com.google.protobuf.ByteString inMemoryDate_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The next message is a serialized LogicalPlan
     * </pre>
     *
     * <code>optional bytes in_memory_date = 3 [json_name = "inMemoryDate"];</code>
     * @return Whether the inMemoryDate field is set.
     */
    @java.lang.Override
    public boolean hasInMemoryDate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The next message is a serialized LogicalPlan
     * </pre>
     *
     * <code>optional bytes in_memory_date = 3 [json_name = "inMemoryDate"];</code>
     * @return The inMemoryDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getInMemoryDate() {
      return inMemoryDate_;
    }
    /**
     * <pre>
     * The next message is a serialized LogicalPlan
     * </pre>
     *
     * <code>optional bytes in_memory_date = 3 [json_name = "inMemoryDate"];</code>
     * @param value The inMemoryDate to set.
     * @return This builder for chaining.
     */
    public Builder setInMemoryDate(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      inMemoryDate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The next message is a serialized LogicalPlan
     * </pre>
     *
     * <code>optional bytes in_memory_date = 3 [json_name = "inMemoryDate"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInMemoryDate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      inMemoryDate_ = getDefaultInstance().getInMemoryDate();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SubmitZinggJob)
  }

  // @@protoc_insertion_point(class_scope:SubmitZinggJob)
  private static final zingg.spark.connect.proto.SubmitZinggJob DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new zingg.spark.connect.proto.SubmitZinggJob();
  }

  public static zingg.spark.connect.proto.SubmitZinggJob getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubmitZinggJob>
      PARSER = new com.google.protobuf.AbstractParser<SubmitZinggJob>() {
    @java.lang.Override
    public SubmitZinggJob parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubmitZinggJob> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubmitZinggJob> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public zingg.spark.connect.proto.SubmitZinggJob getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

