// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connect_plugins.proto

// Protobuf Java Version: 3.25.3
package zingg.spark.connect.proto;

public interface SubmitZinggJobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubmitZinggJob)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string args = 1 [json_name = "args"];</code>
   * @return The args.
   */
  java.lang.String getArgs();
  /**
   * <code>string args = 1 [json_name = "args"];</code>
   * @return The bytes for args.
   */
  com.google.protobuf.ByteString
      getArgsBytes();

  /**
   * <code>string options = 2 [json_name = "options"];</code>
   * @return The options.
   */
  java.lang.String getOptions();
  /**
   * <code>string options = 2 [json_name = "options"];</code>
   * @return The bytes for options.
   */
  com.google.protobuf.ByteString
      getOptionsBytes();
}
