# conda.recipe/meta.yaml
package:
  name: zingg
  version: 0.4.0

source:
  # git_url: https://github.com/zinggAI/zingg.git
  git_url: https://github.com/gnanaprakash-ravi/zingg.git
  git_tag: 0.4.0
  script: python setup.py sdist

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed $PREFIX

requirements:
  build:
    - python==3.8
  run:
    - python==3.8
    - py4j==0.10.9
    - pandas
    - seaborn
    - matplotlib
    - sphinx
    - sphinx-rtd-theme
    - pyspark

test:
  imports:
    - zingg

about:
  home: https://github.com/zinggAI/zingg
  license: GNU Affero General Public License v3
  summary: Zingg Entity Resolution, Data Mastering, and Deduplication
